spring:
  application:
    name: AZAP Travel Insurance API
  datasource:
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
  jackson:
    property-naming-strategy: KEBAB_CASE
  data:
    rest:
      base-path: /data-api

management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true

info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@
